/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffe16d",
        "on-surface-variant": "#554336",
        "on-tertiary-fixed": "#281719",
        "primary-fixed": "#ffdcc3",
        "surface": "#fff8f6",
        "on-secondary-container": "#201c00",
        "on-primary-fixed-variant": "#574435",
        "outline": "#857368",
        "on-primary-fixed": "#2b1708",
        "on-surface": "#231a14",
        "secondary-container": "#ffeeab",
        "surface-container": "#f8eee8",
        "on-tertiary-container": "#400010",
        "tertiary-container": "#ffdae2",
        "on-secondary-fixed": "#201c00",
        "on-surface-variant": "#554336",
        "on-surface-fixed": "#231a14",
        "surface-container-high": "#f2e8e2",
        "surface-container-low": "#fff1eb",
        "on-surface-fixed-variant": "#554336",
        "on-primary-container": "#2b1708",
        "on-secondary": "#363000",
        "outline-variant": "#d9c4b7",
        "scrim": "#000000",
        "primary": "#8e4e00",
        "on-primary": "#ffffff",
        "primary-container": "#ffdcc3",
        "secondary": "#6a6000",
        "on-secondary-fixed-variant": "#504900",
        "on-tertiary-fixed-variant": "#71343a",
        "tertiary": "#94444b",
        "on-tertiary": "#ffffff",
        "surface-container-highest": "#ecdcd3",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#410002",
        "surface-container-lowest": "#ffffff",
        "surface-bright": "#fff8f6",
        "surface-dim": "#e8d8d0",
        "surface-variant": "#f4dfd3",
      },
      fontFamily: {
        serif: ["Noto Serif", "serif"],
        sans: ["Manrope", "sans-serif"],
      },
      borderRadius: {
        "none": "0",
        "sm": "0.125rem",
        "DEFAULT": "4px",
        "md": "0.375rem",
        "lg": "0.5rem",
        "full": "9999px",
        "large": "12px",
        "xl": "1rem",
        "2xl": "2rem",
        "3xl": "3rem",
      },
    }
  },
  plugins: [],
}
